//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.15 at 09:15:08 PM CET 
//


package tp.data;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the tp.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Demande_QNAME = new QName("http://data.tp/", "demande");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tp.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Demande }
     * 
     */
    public Demande createDemande() {
        return new Demande();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Demande }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://data.tp/", name = "demande")
    public JAXBElement<Demande> createDemande(Demande value) {
        return new JAXBElement<Demande>(_Demande_QNAME, Demande.class, null, value);
    }

}
